/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "GLCD.h"
#include "Backlight.h"
#include "Backlight_aliases.h"
#include "ADCInput.h"
#include "A_Interrupt.h"
#include "JoyX.h"
#include "JoyX_aliases.h"
#include "R_LED.h"
#include "R_LED_aliases.h"
#include "G_LED.h"
#include "G_LED_aliases.h"
#include "B_LED.h"
#include "B_LED_aliases.h"
#include "Timer_1.h"
#include "Clock_1.h"
#include "JoyY.h"
#include "JoyY_aliases.h"
#include "GLCD_Reset.h"
#include "GLCD_Reset_aliases.h"
#include "GLCD_SPIM_UDB.h"
#include "GLCD_SPIM_UDB_PVT.h"
#include "GLCD_SCLK.h"
#include "GLCD_SCLK_aliases.h"
#include "GLCD_MOSI.h"
#include "GLCD_MOSI_aliases.h"
#include "GLCD_SS.h"
#include "GLCD_SS_aliases.h"
#include "ADCInput_IRQ.h"
#include "ADCInput_intClock.h"
#include "GLCD_SPIM_UDB_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

