# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\GIT\Microcontroller System Design Projects\Hw7- Tilt Control Star Blasters\Clineq_Quinton_HW7.cydsn\Clineq_Quinton_HW7.cyprj
# Date: Wed, 22 May 2019 05:07:51 GMT
#set_units -time ns
create_clock -name {I2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {Clock_1(FFB)} -period 100000 -waveform {0 50000} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {GLCD_SPIM_UDB_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 5} [list [get_pins {ClockBlock/udb_div_0}]]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 15 31} [list]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 2401 4801} [list]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for D:\GIT\Microcontroller System Design Projects\Hw7- Tilt Control Star Blasters\Clineq_Quinton_HW7.cydsn\TopDesign\TopDesign.cysch
# Project: D:\GIT\Microcontroller System Design Projects\Hw7- Tilt Control Star Blasters\Clineq_Quinton_HW7.cydsn\Clineq_Quinton_HW7.cyprj
# Date: Wed, 22 May 2019 05:07:48 GMT
